### ISSUE TITLE
Evaluate formatting in description / warning

### ISSUE THREAD

**Issue by ewoerner** [bannergress/website#310]
* Maybe markdown?

**Comment by simbabque** [comment]
I would love to give this a shot. I've played around a bit and have come up with the following plan.

- all of this can be done client-side
- markdown makes the most sense, it's simple to use and most people know it, and there is great parsing support already
- use [react-markdown](https://github.com/remarkjs/react-markdown), as this seems to be well supported flexible and stable. We don't need most of its features, but other products are not as active. It also brings XSS protection out of the box.
- there should be a very restricted list of allowed syntax elements so as not to break the page, and also to not allow external external resources to be displayed. I am thinking:
    - bold and italic
    - line breaks and paragraphs
    - ordered and unordered lists
    - I am unsure about links... I think they make sense and you can already put them in now, but they don't render as clickable; it may make sense for things like "here are the opening hours of the park"

  When disallowed markup is used, we can either strip the entire thing completely, or only strip the markup and keep processing children, so headings would turn into plain text

I think this would need changes in the following places:
- `BannerInfoCard`: render the markdown
- `CreateBanner`: point out that it supports markdown, possibly a preview as well as an optional bigger change?

I have a working example that takes most of the above into account. I don't have tests, as my knowledge of how React works is limited. I also don't have example data coming from the API, only hard-coded into the page.

![example rendering](https://github.com/bannergress/website/assets/1125067/12c3c53d-f1ee-4d8d-8af2-d642def0db6d)

If someone could work with me to get testing set up better, I'd be happy to give this a shot.

**Comment by simbabque** [comment]
I've pushed a first draft, but haven't opened a PR yet. An example description including XSS can be found in banner `london-skyline-830f`.
