### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by ewoerner** [bannergress/website#356]
![image](https://github.com/bannergress/website/assets/6642053/1dca619c-1490-435f-8af3-c191ef5c87dc)
![image](https://github.com/bannergress/website/assets/6642053/84a356ea-fdc2-4424-90ab-151aad2f5486)

**Comment by KirDE** [comment]
![image](https://github.com/bannergress/website/assets/12144262/d95e8f24-1f42-4992-84df-398e057089dc)
spanish translation
